// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswersFormat } from "./AnswersFormat";
import type { CompletedRequestStatus } from "./CompletedRequestStatus";
import type { PermissionDecision } from "./PermissionDecision";
import type { JsonValue } from "./serde_json/JsonValue";

export type AgentStateCompletedRequest = { tool: string, arguments: JsonValue, createdAt?: number | null, completedAt?: number | null, status: CompletedRequestStatus, reason: string | null, mode: string | null, decision: PermissionDecision | null, allowTools: Array<string> | null, answers: AnswersFormat | null, };
