// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStateCompletedRequest } from "./AgentStateCompletedRequest";
import type { AgentStateRequest } from "./AgentStateRequest";

export type AgentState = { controlledByUser?: boolean | null, requests?: { [key in string]: AgentStateRequest } | null, completedRequests?: { [key in string]: AgentStateCompletedRequest } | null, };
