// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageDeltaData = { messageId: string, localId: string | null, text: string, isFinal: boolean, seq: number | null, };
