// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataSummary } from "./MetadataSummary";
import type { StartedBy } from "./StartedBy";
import type { WorktreeMetadata } from "./WorktreeMetadata";

export type Metadata = { path: string, host: string, version: string | null, name: string | null, os: string | null, summary: MetadataSummary | null, machineId: string | null, claudeSessionId: string | null, codexSessionId: string | null, geminiSessionId: string | null, opencodeSessionId: string | null, tools: Array<string> | null, slashCommands: Array<string> | null, homeDir: string | null, happyHomeDir: string | null, happyLibDir: string | null, happyToolsDir: string | null, startedFromRunner: boolean | null, hostPid: number | null, startedBy: StartedBy | null, lifecycleState: string | null, lifecycleStateSince: number | null, archivedBy: string | null, archiveReason: string | null, 
/**
 * Can be null or absent
 */
flavor?: string | null, worktree: WorktreeMetadata | null, };
