// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelMode } from "./ModelMode";
import type { SessionSummaryMetadata } from "./SessionSummaryMetadata";
import type { TodoProgress } from "./TodoProgress";

export type SessionSummary = { id: string, active: boolean, thinking: boolean, activeAt: number, updatedAt: number, metadata: SessionSummaryMetadata | null, todoProgress: TodoProgress | null, pendingRequestsCount: number, modelMode: ModelMode | null, };
