// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SummaryText } from "./SummaryText";
import type { WorktreeMetadata } from "./WorktreeMetadata";

export type SessionSummaryMetadata = { name: string | null, path: string, machineId: string | null, summary: SummaryText | null, flavor?: string | null, worktree: WorktreeMetadata | null, };
