// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeMetadata = { basePath: string, branch: string, name: string, worktreePath: string | null, createdAt: number | null, };
